### ISSUE TITLE
Build into an actual program?

### ISSUE THREAD

**Issue by monabat79** [1029chris/dont-get-a-virus#1]
I think if you build it it will be available as an actual program, so that you don't always have to drag the folder onto `Love2D`. Not sure how to do this, but I guess [Mari0](http://stabyourself.net/mari0/) did this.

Also, hi Chris :)

**Comment by Sarah-Duck** [comment]
I'll do that eventually, but the game isn't ready yet. Give me a few weeks, and I'll have a demo ready!

**Comment by monabat79** [comment]
Okay! I might bring some more features to make you have something to work on :)

**Comment by monabat79** [comment]
I think you can also turn the folder into a `.zip` file then convert that file into `.love`
Both can be opened with winrar, and `.love` can be opened using `love`, to play.

**Comment by monabat79** [comment]
This works.
![Imgur](http://i.imgur.com/gpSbC1W.png)

**Comment by Sarah-Duck** [comment]
Yep, that works. I've been doing that when sending the game to friends. Also, I just wanted to let you know: I'm doing this game on my own. This is a learning experience for me, so I don't want anyone else to contribute code. Just thought I'd let you know.

**Comment by monabat79** [comment]
If I will contribute - then I will just send issues and/or bug reports. But still... Good luck, have fun!

**Comment by monabat79** [comment]
I've also seen some github projects attaching files to releases, like installers.
Maybe you could try attaching the `.love` file, I think it might work.

**Comment by Sarah-Duck** [comment]
I intend to do that for releases, yes. But this game isn't ready yet. I'll do that when I think it's time(Hopefully within a couple weeks).

**Comment by Nikitaw99** [comment]
Atleast Pre-Releases? Like, Alpha builds?
